import React, {useEffect,useRef,useState} from 'react';
import {auth} from '../services/firebaseConfig';
type Item={id:string;label:string;active:boolean};
type Catalog={revision:number;items:Record<string,Item[]>;editable:string[]};
const labels:Record<string,string>={categories:'Plano de contas',paymentMethods:'Formas de pagamento',receiptMethods:'Formas de recebimento',deliveryMethods:'Formas de cobrança',paidBy:'Responsáveis pelo pagamento',authorizedBy:'Autorizadores',extras:'Cobranças extras',banks:'Contas bancárias',interestRates:'Taxas de juros'};
async function request(body?:unknown):Promise<Catalog>{
 if(!auth.currentUser)throw Error('Entre novamente.');
 const r=await fetch('/api/financial-entries/maintenance',{method:body?'POST':'GET',headers:{Authorization:`Bearer ${await auth.currentUser.getIdToken()}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});
 const data=await r.json();if(!r.ok)throw Error(data.error||'Não foi possível concluir.');return data;
}
export default function MaintenanceModal({onClose,api=request}:{onClose:()=>void;api?:typeof request}){
 const dialog=useRef<HTMLDialogElement>(null),gate=useRef(false);
 const [data,setData]=useState<Catalog|null>(null),[group,setGroup]=useState('categories'),[search,setSearch]=useState(''),[editing,setEditing]=useState<Item|null>(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[review,setReview]=useState(false);
 async function load(){setBusy(true);setError('');try{setData(await api());setEditing(null);setReview(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{dialog.current?.showModal();void load();},[]);
 const editable=data?.editable.includes(group);
 async function save(){if(gate.current||!editing||!data)return;gate.current=true;setBusy(true);setError('');try{setData(await api({group,revision:data.revision,...editing,reason}));setEditing(null);setReview(false);setMessage('Alteração salva e registrada no histórico de manutenção.');}catch(e){setError((e as Error).message+' Recarregue para conferir o cadastro antes de tentar novamente.');setReview(false);}finally{setBusy(false);gate.current=false;}}
 const field='w-full rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-800 p-3';
 return <dialog ref={dialog} onCancel={e=>{e.preventDefault();if(!busy)onClose();}} aria-labelledby="maintenance-title" className="w-[min(1000px,95vw)] max-h-[90vh] rounded-2xl bg-white dark:bg-slate-900 text-slate-900 dark:text-slate-100 p-0 shadow-2xl backdrop:bg-black/60">
 <header className="sticky top-0 bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-700 p-5 flex items-center justify-between gap-4"><div><h2 id="maintenance-title" className="text-xl font-semibold">Manutenção</h2><p className="text-sm text-slate-500">Cadastros e parâmetros do Financeiro</p></div><button disabled={busy} onClick={onClose} className="rounded-lg border px-4 py-2">Fechar</button></header>
 <div className="grid md:grid-cols-[230px_1fr] gap-6 p-5"><nav aria-label="Cadastros de manutenção" className="space-y-1">{Object.entries(labels).map(([key,label])=><button key={key} disabled={busy} onClick={()=>{setGroup(key);setEditing(null);setReview(false);setSearch('');setError('');setMessage('');}} className={`block w-full text-left px-3 py-2 rounded-lg ${group===key?'bg-blue-600 text-white':'hover:bg-slate-100 dark:hover:bg-slate-800'}`}>{label}</button>)}<a className="block px-3 py-3 text-blue-500" href="https://consultor-fiscal-inteligente-631239634290.us-west1.run.app/?painel=comunicacao&departamento=financeiro" target="_blank" rel="noreferrer">Templates e agendamentos ↗</a></nav>
 <section className="min-w-0"><div className="flex flex-wrap items-center gap-3 mb-4"><h3 className="text-lg font-semibold flex-1">{labels[group]}</h3><button disabled={busy} onClick={load} className="border rounded-lg px-3 py-2">Recarregar</button>{editable&&<button disabled={busy} onClick={()=>{setEditing({id:'',label:'',active:true});setReason('');setReview(false);setMessage('');}} className="bg-blue-600 text-white rounded-lg px-4 py-2">Novo cadastro</button>}</div>
 <p className="text-sm mb-4 text-slate-500">{editable?'Alterações valem para novos lançamentos. O histórico financeiro mantém os dados originais. Inative cadastros que não devem mais ser utilizados.':'Consulta dos parâmetros atuais. Alterações bancárias e de juros exigem revisão da integração.'}</p>
 {error&&<p role="alert" className="p-3 mb-3 bg-red-50 text-red-800 rounded-lg">{error}</p>}{message&&<p role="status" className="p-3 mb-3 bg-green-50 text-green-800 rounded-lg">{message}</p>}
 {editing?<form onSubmit={e=>{e.preventDefault();if(review)void save();else setReview(true);}} className="space-y-4 border rounded-xl p-4"><label className="block">{group==='categories'?'Código - descrição':'Descrição'}<input required maxLength={160} disabled={busy||review} value={editing.label} onChange={e=>setEditing({...editing,label:e.target.value})} className={field}/></label><label className="flex items-center gap-2"><input type="checkbox" disabled={busy||review} checked={editing.active} onChange={e=>setEditing({...editing,active:e.target.checked})}/>Disponível para novos lançamentos</label><label className="block">Motivo da alteração<textarea required minLength={5} maxLength={500} disabled={busy||review} value={reason} onChange={e=>setReason(e.target.value)} className={field}/></label>{review&&<p className="bg-amber-50 text-amber-900 p-3 rounded-lg">Confirme: {editing.label} · {editing.active?'Ativo':'Inativo'}. Nenhum lançamento antigo será regravado.</p>}<div className="flex gap-3"><button disabled={busy} className="bg-blue-600 text-white rounded-lg px-4 py-2">{busy?'Salvando…':review?'Confirmar alteração':'Revisar alteração'}</button><button type="button" disabled={busy} onClick={()=>review?setReview(false):setEditing(null)} className="border rounded-lg px-4 py-2">Voltar</button></div></form>:<><label className="block mb-3">Pesquisar<input value={search} onChange={e=>setSearch(e.target.value)} className={field}/></label><div className="max-h-[50vh] overflow-auto rounded-lg border border-slate-200 dark:border-slate-700"><table className="w-full text-sm"><thead><tr className="text-left bg-slate-100 dark:bg-slate-800"><th className="p-3">Descrição</th><th className="p-3">Situação</th>{editable&&<th className="p-3">Ação</th>}</tr></thead><tbody>{data?.items[group]?.filter(x=>x.label.toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(item=><tr key={item.id} className="border-t border-slate-200 dark:border-slate-700"><td className="p-3">{item.label}</td><td className="p-3">{item.active?'Ativo':'Inativo'}</td>{editable&&<td className="p-3"><button disabled={busy} className="text-blue-500 underline" onClick={()=>{setEditing({...item});setReason('');setReview(false);}}>Editar</button></td>}</tr>)}</tbody></table>{!data&&<p className="p-3">{busy?'Carregando…':'Cadastro indisponível.'}</p>}</div></>}
 </section></div></dialog>;
}
